services:
  db.connection:
    class: Glassy::MongoODM::Connection
    singleton: true
    kwargs:
      conn_string: '%db.server:String%'
      default_database: '%db.default_database:String%'

  db.make_migration_command:
    class: Glassy::MongoODM::Commands::MakeMigration
    kwargs:
      input: '@console.input'
      output: '@console.output'
      kernel: '@kernel'
    tag:
      - console.command

  db.migrate_command:
    class: Glassy::MongoODM::Commands::Migrate
    kwargs:
      input: '@console.input'
      output: '@console.output'
      container: '@container'
      repository: '@db.migration_repository'
    tag:
      - console.command

  db.migration_repository:
    class: Glassy::MongoODM::MigrationRepository
    kwargs:
      connection: '@db.connection'
